id: PDB5C4CC1
initial_creation_type: input
source_metadata:
  Title: Mahāyānaviṁśikā
  Editor: Bhattacharya, V.
  Publisher: '-'
  Place of Publication: '-'
  Year: '1929'
  Mahāyānaviṃśikā:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:39:25.192001'
last_modified_at: '2022-03-08T16:39:25.192009'
